export const testResponse = [
    {
        "id": 10,
        "name": "USD",
        "symbol": "USD",
        "interest": 0.05,
        "image": "/assets/currencies/USDX.svg",
        "api_id": "None",
        "decimals": 0,
        "disabled": false,
        "admin_disabled": false,
        "usd_value": 1,
        "d_fee": 0,
        "e_fee": 0,
        "w_fee": 0,
        "spread": 0,
        "min_deposit": 100,
        "min_exchange": 0,
        "token": false,
        "kraken_fee": 0,
        "address": "0x7e66adFd3cA1Ce405627aC52e25c61dBeb3b58E4",
        "network": null,
        "usd_price": 1.04,
        "balance": 150,
        "earn": 0,
        "credit": 0,
        "token_fee": 0,
        "network_symbol": ""
    },
    {
        "id": 11,
        "name": "EUR",
        "symbol": "EUR",
        "interest": 0.08,
        "image": "/assets/currencies/EURX.svg",
        "api_id": "None",
        "decimals": 0,
        "disabled": false,
        "admin_disabled": false,
        "usd_value": 0.99885,
        "d_fee": 0,
        "e_fee": 0,
        "w_fee": 0,
        "spread": 0.015,
        "min_deposit": 50,
        "min_exchange": 0,
        "token": false,
        "kraken_fee": 0,
        "address": "0x7e66adFd3cA1Ce405627aC52e25c61dBeb3b58E4",
        "network": null,
        "usd_price": 0,
        "balance": 300,
        "earn": 0,
        "credit": 0,
        "token_fee": 0,
        "network_symbol": ""
    },
    {
        "id": 12,
        "name": "GBP",
        "symbol": "GBP",
        "interest": 0.08,
        "image": "/assets/currencies/GBPX.svg",
        "api_id": "None",
        "decimals": 0,
        "disabled": false,
        "admin_disabled": false,
        "usd_value": 1.14255,
        "d_fee": 0,
        "e_fee": 0,
        "w_fee": 0,
        "spread": 0.02,
        "min_deposit": 50,
        "min_exchange": 10,
        "token": false,
        "kraken_fee": 0,
        "address": "0x7e66adFd3cA1Ce405627aC52e25c61dBeb3b58E4",
        "network": null,
        "usd_price": 0,
        "balance": 500,
        "earn": 0,
        "credit": 0,
        "token_fee": 0,
        "network_symbol": ""
    }
]
